version: "3"

services:
    web:
        hostname: web
        build:
            context: .
            dockerfile: Dockerfile_app
        image: ${IMAGE_PREFIX}_web:${IMAGE_VERSION}
        container_name: ${IMAGE_PREFIX}_web
        command: uvicorn main:app --host 0.0.0.0 --port 8000
        volumes:
            - ./app:/app
        ports:
            - "${PORT_WEB}:8000"
        env_file:
            - .env
        restart: always
        depends_on:
            - db

    redis:
        image: redis:latest
        container_name: "${IMAGE_PREFIX}_redis"
        ports:
            - "${PORT_REDIS}:6379"

    celery_worker:
        container_name: ${IMAGE_PREFIX}_celery_worker
        build:
            context: .
            dockerfile: Dockerfile_app
        image: ${IMAGE_PREFIX}_worker:${IMAGE_VERSION}
        command: celery -A tasks.celery_worker worker --pool=solo --loglevel=info
        volumes:
            - ./app:/app
        depends_on:
            - redis
            - web
        restart: always
        env_file:
            - .env

    flower:
        container_name: ${IMAGE_PREFIX}_flower
        build:
            context: .
            dockerfile: Dockerfile_app
        image: ${IMAGE_PREFIX}_flower:${IMAGE_VERSION}
        command: celery -A tasks.celery_worker flower
        volumes:
            - ./app:/app
        ports:
            - "${PORT_FLOWER}:5555"
        env_file:
            - .env
        depends_on:
            - redis
            - web
            - celery_worker

    db:
        hostname: db
        image: postgres:15
        container_name: ${IMAGE_PREFIX}_database
        volumes:
            - ./data/db:/var/lib/postgresql/data
        ports:
            - "${PORT_POSTGRES}:5432"
        env_file:
            - .env
